import {
  Button,
  Divider,
  Flex,
  Heading,
  Highlight,
  IconButton,
  ListItem,
  Text,
  Tooltip,
  UnorderedList,
  useDisclosure,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "../components/Container";
import { Main } from "../components/Main";
import { Percentage } from "../components/Percentage";
import { ExpenseModal } from "../components/ExpenseModal";
import { useLocalStorage } from "../hooks/useLocalStorage";
import { ExpenseDTO, useExpenseStore } from "../store";
import { useEffect, useState } from "react";
import { DeleteIcon, EditIcon } from "@chakra-ui/icons";
import { DeleteModal } from "../components/DeleteModal";
import { formatToBRL } from "../utils/formatters";
import { TotalSection } from "../components/TotalSection";
import { Expense } from "../components/Expense";

const Home: NextPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const {
    isOpen: isDeleteOpen,
    onOpen: onDeleteOpen,
    onClose: onDeleteClose,
  } = useDisclosure();
  const [storageList] = useLocalStorage<ExpenseDTO[]>("expenseList", []);
  const { setAllExpenses, expenseList } = useExpenseStore();
  const [selectedExpense, setSelectedExpense] = useState<string | null>(null);
  const [modalMode, setModalMode] = useState<"edit" | "idle">("idle");

  useEffect(() => {
    setAllExpenses(storageList);
  }, [storageList]);

  return (
    <Container>
      <Head>
        <title>Expense divider</title>
        <meta
          name="description"
          content="Generated by Futhememe boilerplate generator"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DeleteModal
        isOpen={isDeleteOpen}
        onClose={onDeleteClose}
        expenseId={selectedExpense ?? ""}
      />
      <ExpenseModal
        isOpen={isOpen}
        onClose={onClose}
        mode={modalMode}
        selectedId={selectedExpense ?? ""}
      />
      <Main>
        <Heading textAlign="center">Lançamentos</Heading>
        <Percentage />
        <Tooltip
          placement="bottom"
          label="Clique aqui para adicionar um novo lançamento"
        >
          <Button
            w="100%"
            colorScheme="green"
            onClick={() => {
              setModalMode("idle");
              onOpen();
            }}
          >
            + lançamento
          </Button>
        </Tooltip>
        <Divider />
        <TotalSection />
        {expenseList.map((expense) => (
          <Expense
            key={expense.id}
            name={expense.expenseName}
            total={expense.total}
            firstAmount={expense.esther}
            secondAmount={expense.gustavo}
            onClickEdit={() => {
              setSelectedExpense(expense.id);
              setModalMode("edit");
              onOpen();
            }}
            onClickDelete={() => {
              onDeleteOpen();
              setSelectedExpense(expense.id);
            }}
          />
        ))}
      </Main>
    </Container>
  );
};

export default Home;
