import { Flex, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "../components/Container";
import { Main } from "../components/Main";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Expense divider</title>
        <meta
          name="description"
          content="Generated by Futhememe boilerplate generator"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main></Main>
    </Container>
  );
};

export default Home;
